### ISSUE TITLE
pkg_resources.DistributionNotFound: botocore>=1.7.0,<1.8.0

### ISSUE THREAD

**Issue by s-baron** [fugue/credstash#171]
I'm using pip install awscli==1.11.113 credstash==1.11.0, when I run credstash list I'm getting this error:

Traceback (most recent call last):
  File "/usr/local/bin/credstash", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: botocore>=1.7.0,<1.8.0

**Comment by erichs** [comment]
We're seeing this, also: `pkg_resources.DistributionNotFound: The 'botocore<1.9.0,>=1.8.39' distribution was not found and is required by boto3`

The colliding tooling versions in our setup were: 
awscli==1.14.34
credstash==1.14.0

Doing a `pip install "awscli==1.14.35"` fixed this by pulling in `botocore==1.8.39`
