### ISSUE TITLE
This error has surfaced again..

### ISSUE THREAD

**Issue by mfisher29** [fugue/credstash#187]
Using version 1.13.4, 

```
Traceback (most recent call last):
  File "testConsumerLoop.py", line 5, in <module>
    import ec_lib_adx_consumer_fxns
  File "../../app/ecs/ec_lib_adx_consumer_fxns.py", line 3, in <module>
    import credstash
  File "/Users/mafisher/creatives-backend/services/eligibility-adx-consumer/QA/tests/credstash.py", line 55, in <module>
    'RIPEMD': hashes.RIPEMD160,
AttributeError: 'module' object has no attribute 'RIPEMD160'
```

Any suggestions?

**Comment by glyph** [comment]
See #178.
