### ISSUE TITLE
putall is missing comment and raises AttributeError

### ISSUE THREAD

**Issue by rene00** [fugue/credstash#218]
```
$ python credstash.py --region=us-west-1 put foo bar
foo has been stored
$ python credstash.py --region=us-west-1 getall > foo.json
$ python credstash.py --region=us-west-1 putall @foo.json
Traceback (most recent call last):
  File "credstash.py", line 935, in <module>
    main()
  File "credstash.py", line 919, in main
    putAllSecretsAction(args, region, **session_params)
  File "credstash.py", line 246, in func_wrapper
    return func(*args, **kwargs)
  File "credstash.py", line 411, in putAllSecretsAction
    putSecretAction(args, region, **session_params)
  File "credstash.py", line 246, in func_wrapper
    return func(*args, **kwargs)
  File "credstash.py", line 386, in putSecretAction
    context=args.context, digest=args.digest, comment=args.comment,
AttributeError: 'Namespace' object has no attribute 'comment'
```

**Comment by CaseyLabs** [comment]
Just following up on this issue, as I've just encountered it. @alex-luminal - would it be possible to have this PR for credstash merged in?

Current issue encountered:

```
credstash getall > secrets.json

credstash putall @secrets.json

Traceback (most recent call last):
  File "/usr/local/bin/credstash", line 11, in <module>
    sys.exit(main())
  File "/usr/local/bin/credstash.py", line 919, in main
    putAllSecretsAction(args, region, **session_params)
  File "/usr/local/bin/credstash.py", line 246, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/bin/credstash.py", line 411, in putAllSecretsAction
    putSecretAction(args, region, **session_params)
  File "/usr/local/bin/credstash.py", line 246, in func_wrapper
    return func(*args, **kwargs)
  File "/usr/local/bin/credstash.py", line 386, in putSecretAction
    context=args.context, digest=args.digest, comment=args.comment,
AttributeError: 'Namespace' object has no attribute 'comment'
```
