### ISSUE TITLE
storing empty string fails on retrieval

### ISSUE THREAD

**Issue by WrathOfChris** [fugue/credstash#57]
Appears that `data['contents']` is set to `None` instead of `""` when an empty string is passed for storage, which causes the decode steps to fail.

Example:
```
credstash put empty_string_key ""
credstash get empty_string_key
Traceback (most recent call last):
  File "/Virtualenvs/default/bin/credstash", line 11, in <module>
    sys.exit(main())
  File "/Virtualenvs/default/bin/credstash.py", line 474, in main
    context=args.context))
  File "/Virtualenvs/default/bin/credstash.py", line 251, in getSecret
    hmac = HMAC(hmac_key, msg=b64decode(material['contents']),
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 73, in b64decode
    return binascii.a2b_base64(s)
TypeError: must be string or buffer, not None
```

**Comment by alex-luminal** [comment]
Can you double-check to make sure that you're running the latest version? This is what I get:
```
$ credstash put empty_string_key ""
$ credstash get empty_string_key
Item {'name': 'empty_string_key'} couldn't be found.
```

Also, the line numbers in your traceback dont line up with whats in master. 

Thanks!

**Comment by alex-luminal** [comment]
I'm having trouble repo'ing this issue. Going to close for now. Feel free to re-open if this is still an issue for you
