### ISSUE TITLE
credstash 1.9.0 does not seem to respect `-r` option (region)

### ISSUE THREAD

**Issue by romanrev** [fugue/credstash#66]
```
[user@machine ~]$ pip list | grep credstash
credstash (1.9.0)
[user@machine ~]$ credstash -r ap-southeast-2 list
Traceback (most recent call last):
  File "/usr/local/bin/credstash", line 9, in <module>
    load_entry_point('credstash==1.9.0', 'console_scripts', 'credstash')()
  File "/usr/local/bin/credstash.py", line 485, in main
    credential_list = listSecrets(region=region, table=args.table)
  File "/usr/local/bin/credstash.py", line 171, in listSecrets
    ExpressionAttributeNames={"#N": "name"})
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/factory.py", line 455, in do_action
    response = action(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/boto3/resources/action.py", line 79, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the Scan operation: User: arn:aws:sts::<AWS account id>:assumed-role/<role>/<instance id> is not authorized to perform: dynamodb:Scan on resource: arn:aws:dynamodb:us-east-1:<AWS account id>:table/credential-store

# And now using the environment variable:
[user@machine ~]$ AWS_DEFAULT_REGION=ap-southeast-2 credstash list
key1   -- version 1
key2   -- version 1
key3   -- version 1
```

**Comment by romanrev** [comment]
Looks like this is caused by this code which always defaults to the `DEFAULT_REGION`:

**Comment by alex-luminal** [comment]
Just pushed a new version to pypi that includes the fix. release notes here: https://github.com/fugue/credstash/releases/tag/v1.9.1
